spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true